name: Release & Publish via .nuspec

on:
  push:
    tags:
      - 'v*.*.*'   # ex: v1.0.5

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build all projects
        run: dotnet build --configuration Release

      - name: Install NuGet CLI
        run: dotnet tool install --global NuGet.CommandLine --version 6.*

      - name: Add NuGet CLI to PATH
        run: echo "${{ runner.tool_cache }}/dotnet-tools/bin" >> $GITHUB_PATH

      - name: Pack with .nuspec
        working-directory: src/NexMediator
        run: |
          nuget pack NexMediator.nuspec \
            -BasePath . \
            -OutputDirectory ../NexMediatorNugetPackage

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push NexMediatorNugetPackage/NexMediator.${VERSION}.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
