name: Release & Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Publish NuGet Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: |
          dotnet pack src/NexMediator.Core/NexMediator.Core.csproj \
            --configuration Release \
            --no-build \
            --include-symbols \
            /p:PackageVersion=${PACKAGE_VERSION} \
            --output ./nupkg

      - name: Publish to NuGet
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
