name: Release & Publish via .nuspec

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.0.5

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        shell: powershell
        run: |
          $ver = $Env:GITHUB_REF -replace 'refs/tags/v',''
          echo "VERSION=$ver" >> $Env:GITHUB_ENV

      - name: Build all projects
        run: dotnet build --configuration Release

      - name: Pack with .nuspec
        run: |
          nuget pack src\NexMediator\NexMediator.nuspec `
            -BasePath src\NexMediator `
            -OutputDirectory nupkg

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push nupkg\NexMediator.${{ env.VERSION }}.nupkg `
            --api-key ${{ secrets.NUGET_API_KEY }} `
            --source https://api.nuget.org/v3/index.json `
            --skip-duplicate
