name: Release & Publish via .nuspec

on:
  push:
    tags:
      - 'v*.*.*'   # ex: v1.0.5

jobs:
  release:    
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Extract version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $Env:GITHUB_ENV

      - name: Build all projects
        run: dotnet build --configuration Release

      - name: Pack with .nuspec
        working-directory: src\NexMediator
        run: |
          nuget pack NexMediator.nuspec `
            -BasePath . `
            -OutputDirectory ..\NexMediatorNugetPackage

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push NexMediatorNugetPackage\NexMediator.$Env:VERSION.nupkg `
            --api-key ${{ secrets.NUGET_API_KEY }} `
            --source https://api.nuget.org/v3/index.json `
            --skip-duplicate
