name: Release & Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'   # ex: v1.0.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build -c Release --no-restore

      - name: Pack NexMediator meta-package
        run: |
          dotnet pack src/NexMediator/NexMediator.csproj \
            -c Release \
            --no-build \
            --include-symbols \
            /p:PackageVersion=${VERSION} \
            -o ./nupkg

      - name: Publish to NuGet
        run: |
          dotnet nuget push ./nupkg/NexMediator.*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
